"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const version = JSON.parse(fs.readFileSync(
  path.join(__dirname, "..", "amarillo-version.json"),
  "utf8"
));
const pluginSource = fs.readFileSync(
  path.join(__dirname, "..", "src", "plugin", "Amarillo.lua"),
  "utf8"
);
const watcherSource = fs.readFileSync(
  path.join(__dirname, "..", "src", "plugin-src", "90_watchers_loops.lua"),
  "utf8"
);
const {
  readManifest,
  generatePluginSource
} = require("../scripts/build-plugin");

const expectedPluginModules = [
  "00_bootstrap.lua",
  "10_settings_status.lua",
  "20_http.lua",
  "30_values_properties.lua",
  "40_snapshot_sync.lua",
  "50_commands.lua",
  "60_connection_flow.lua",
  "70_privileged_actions.lua",
  "80_ui.lua",
  "90_watchers_loops.lua"
];

test("Roblox plugin source is generated from ordered plugin-src modules", () => {
  const manifestModules = readManifest();

  assert.deepEqual(manifestModules, expectedPluginModules);
  assert.equal(new Set(manifestModules).size, manifestModules.length);
  assert.match(pluginSource, /generated by scripts\/build-plugin\.ts/);
  for (const moduleName of expectedPluginModules) {
    assert.match(pluginSource, new RegExp(`-- >>> src/plugin-src/${moduleName}`));
    assert.ok(fs.existsSync(path.join(__dirname, "..", "src", "plugin-src", moduleName)), moduleName);
  }
});

test("generated Roblox plugin is synchronized with plugin-src modules", () => {
  assert.equal(pluginSource, generatePluginSource());
});

test("Roblox plugin declares Amarillo version and protocol constants", () => {
  assert.match(pluginSource, /local PLUGIN_VERSION = "\d+\.\d+\.\d+"/);
  assert.match(pluginSource, /local AMARILLO_PROTOCOL_VERSION = \d+/);
});

test("Roblox plugin sends version metadata in handshake, polling, snapshots, and command results", () => {
  assert.match(pluginSource, /pluginVersion = PLUGIN_VERSION/);
  assert.match(pluginSource, /pluginProtocolVersion = AMARILLO_PROTOCOL_VERSION/);
  assert.match(pluginSource, /privilegedActionConfirmationEnabled = state\.confirmPrivilegedActions == true/);
  assert.match(pluginSource, /addVersionPayload\(body\)/);
  assert.match(pluginSource, /addVersionPayload\(bodyTable\)/);
  assert.match(pluginSource, /pluginVersionQuery\(\)/);
});

test("Roblox plugin gates run_code behind privileged action confirmation", () => {
  assert.match(pluginSource, /confirmPrivilegedActions = true/);
  assert.match(pluginSource, /if command\.type == "run_code" then[\s\S]+showDestructiveConfirmation\(command\)[\s\S]+executeRunCode\(command\)/);
  assert.match(pluginSource, /title = "Confirm Luau Execution"/);
  assert.match(pluginSource, /Privileged action confirmation/);
  assert.match(pluginSource, /run_code, modify_property, create_instance, delete_instance, or insert_model/);
});

test("Roblox plugin keeps its dock widget hidden during playtest", () => {
  assert.match(pluginSource, /local function isExperienceRunning\(\)[\s\S]+RunService:IsRunning\(\)/);
  assert.match(pluginSource, /local function showPluginWidget\(\)[\s\S]+if isExperienceRunning\(\) then\s+hidePluginWidget\(\)\s+return false/);
  assert.match(pluginSource, /DockWidgetPluginGuiInfo\.new\(\s+Enum\.InitialDockState\.Right,\s+false,\s+true,/);
  assert.match(pluginSource, /toolbarButton\.Click:Connect\(function\(\)\s+togglePluginWidget\(\)\s+end\)/);
  assert.match(pluginSource, /if isExperienceRunning\(\) and widget and widget\.Enabled then\s+hidePluginWidget\(\)\s+end/);
  assert.doesNotMatch(pluginSource, /widget\.Enabled = true\s+loadSettings\(\)/);
});

test("Roblox plugin keeps the privileged action confirmation toggle in Settings", () => {
  assert.match(pluginSource, /state\.ui\.confirmPropToggle = makeButton/);
  assert.match(pluginSource, /state\.ui\.homeConfirmPropToggle = makeButton/);
  assert.match(pluginSource, /setPrivilegedActionConfirmation = function\(enabled, source\)/);
  assert.match(pluginSource, /updatePrivilegedActionConfirmationUi = function\(\)/);
  assert.match(pluginSource, /confirmPrivilegedActions = state\.confirmPrivilegedActions/);
  assert.match(pluginSource, /if saved\.confirmPrivilegedActions ~= nil then/);
  assert.match(pluginSource, /set_privileged_action_confirmation/);
  assert.match(pluginSource, /postCommandResult\(command\.id, true, \{\s+result = enabled and "Privileged action confirmation enabled\."/);
  assert.match(pluginSource, /updatePrivilegedActionConfirmationUi\(\)\s+saveSettings\(\)/);
});

test("Roblox plugin preflights and safely recovers missing sync mounts", () => {
  assert.match(pluginSource, /local function preflightProjectMounts\(projectSnapshot\)/);
  assert.match(pluginSource, /local function validateMountContainerRecovery\(segments\)/);
  assert.match(pluginSource, /local function ensureRecoverableMountContainer\(segments\)/);
  assert.match(pluginSource, /return game:GetService\(segment\)/);
  assert.match(pluginSource, /Instance\.new\("Folder"\)/);
  assert.match(pluginSource, /Mount integrity found:/);
  assert.match(pluginSource, /Mount integrity recreated:/);
  assert.match(pluginSource, /Mount integrity blocked:/);
  assert.match(pluginSource, /Mount integrity ignored:/);
  assert.match(pluginSource, /Sync blocked: unsafe or missing mount base\(s\):/);
  assert.match(pluginSource, /local container = mountContainers\[mount\]/);
  assert.doesNotMatch(pluginSource, /Mount not found:/);
});

test("Roblox plugin does not fail create_instance after successful parenting because of waypoints", () => {
  assert.match(pluginSource, /local okStartWaypoint, startWaypointErr = pcall\(function\(\)\s+ChangeHistoryService:SetWaypoint\("MCP create instance: " \.\. className\)/);
  assert.match(pluginSource, /return newInstance\s+end\)\s+local fullName = nil/);
  assert.match(pluginSource, /local okDoneWaypoint, doneWaypointErr = pcall\(function\(\)\s+ChangeHistoryService:SetWaypoint\("MCP create instance done"\)/);
  assert.match(pluginSource, /create_instance completion waypoint warning/);
  assert.match(pluginSource, /fullName = ok and fullName or nil/);
  assert.match(pluginSource, /reasonCode = ok and nil or "CREATE_FAILED"/);
});

test("Roblox plugin reuses the serialized snapshot body for automatic snapshot cache checks", () => {
  assert.match(pluginSource, /lastSnapshotBodyJson = nil/);
  assert.match(pluginSource, /local bodyJson = HttpService:JSONEncode\(bodyTable\)/);
  assert.match(pluginSource, /bodyJson == state\.lastSnapshotBodyJson/);
  assert.doesNotMatch(pluginSource, /JSONEncode\(snapshot\)/);
});

test("Roblox plugin confirms apply commands with verification snapshots", () => {
  assert.match(pluginSource, /postCommandResult\(command\.id, ok, \{\s+result = message,\s+snapshot = appliedSnapshot,/);
  assert.match(pluginSource, /corrected = correctedDuringApply == true/);
  assert.match(pluginSource, /postCommandResult\(command\.id, ok, \{\s+result = ok and "Patch aplicado" or tostring\(err\),\s+snapshot = appliedSnapshot,/);
});

test("Roblox plugin refreshes open document cache after file patches", () => {
  assert.match(pluginSource, /ScriptEditorService:GetScriptDocuments\(\)/);
  assert.match(pluginSource, /ScriptEditorService:GetEditorSource\(instance\)/);
  assert.doesNotMatch(pluginSource, /GetEditorDocuments/);
  assert.match(pluginSource, /local function updateScriptSourceIfChanged\(instance, desiredSource, openDocumentSources, force\)/);
  assert.match(pluginSource, /if not force and currentSource == desiredSource then\s+return false, true, nil/);
  assert.match(pluginSource, /local changed, updateOk, updateErr = updateScriptSourceIfChanged\(container, desiredSource, nil, true\)/);
  assert.match(pluginSource, /if not updateOk then\s+error\("Failed to update script source: " \.\. tostring\(updateErr\)\)\s+end/);
  assert.match(pluginSource, /refreshOpenDocumentCache\(\)\s+if changed then\s+ChangeHistoryService:SetWaypoint\("Amarillo Patch: " \.\. container\.Name\)\s+end\s+appliedSnapshot = snapshotCurrentProject\(\)/);
});

test("Roblox plugin stores and sends the daemon session token", () => {
  assert.match(pluginSource, /sessionToken = nil/);
  assert.match(pluginSource, /state\.sessionToken = response\.session and response\.session\.sessionToken or nil/);
  assert.match(pluginSource, /X-Amarillo-Session-Token/);
});

test("Roblox plugin uses adaptive connected polling intervals", () => {
  assert.match(pluginSource, /local POLL_MIN_INTERVAL = 0\.25/);
  assert.match(pluginSource, /local POLL_MAX_INTERVAL = 1\.0/);
  assert.match(pluginSource, /local POLL_IDLE_THRESHOLD_1 = 5\.0/);
  assert.match(pluginSource, /local POLL_IDLE_THRESHOLD_2 = 30\.0/);
  assert.match(pluginSource, /state\.watchers\.currentPollInterval = POLL_MIN_INTERVAL/);
  assert.match(pluginSource, /if #commands > 0 then\s+state\.lastActivityAt = now\(\)\s+state\.watchers\.currentPollInterval = POLL_MIN_INTERVAL/);
  assert.match(pluginSource, /idleTime > POLL_IDLE_THRESHOLD_2[\s\S]+state\.watchers\.currentPollInterval = POLL_MAX_INTERVAL/);
  assert.match(pluginSource, /idleTime > POLL_IDLE_THRESHOLD_1[\s\S]+state\.watchers\.currentPollInterval = 0\.5/);
  assert.match(pluginSource, /task\.wait\(state\.watchers\.currentPollInterval\)/);
});

test("Roblox plugin backs off disconnected offer polling while idle", () => {
  assert.match(pluginSource, /local OFFER_ACTIVE_POLL_INTERVAL = 0\.5/);
  assert.match(pluginSource, /local OFFER_IDLE_POLL_INTERVAL = 1\.5/);
  assert.match(pluginSource, /local OFFER_RETRY_POLL_INTERVAL = 1\.0/);
  assert.match(pluginSource, /state\.watchers\.currentOfferPollInterval = OFFER_IDLE_POLL_INTERVAL/);
  assert.match(pluginSource, /state\.watchers\.currentOfferPollInterval = OFFER_ACTIVE_POLL_INTERVAL/);
  assert.match(pluginSource, /state\.watchers\.currentOfferPollInterval = OFFER_IDLE_POLL_INTERVAL/);
  assert.match(pluginSource, /state\.watchers\.currentOfferPollInterval = OFFER_RETRY_POLL_INTERVAL/);
  assert.match(pluginSource, /task\.wait\(state\.watchers\.currentOfferPollInterval\)/);
});

test("Roblox plugin watcher module avoids top-level locals", () => {
  assert.doesNotMatch(watcherSource, /^local(?:\s+function|\s+)/m);
  assert.match(watcherSource, /state\.watchers = state\.watchers or \{\}/);
  assert.match(watcherSource, /state\.watchers\.markDirty = function\(\)/);
  assert.match(watcherSource, /state\.watchers\.connectScriptEditorWatcher = function\(\)/);
});

test("Roblox plugin caches property metadata while reading live values", () => {
  assert.match(pluginSource, /local propertyNameCache = \{\}/);
  assert.match(pluginSource, /local function propertyNamesForInstance\(instance\)/);
  assert.match(pluginSource, /local className = instance\.ClassName/);
  assert.match(pluginSource, /propertyNameCache\[className\] = propertyNames/);
  assert.match(pluginSource, /local function collectProperties\(instance\)\s+local propertyNames = propertyNamesForInstance\(instance\)/);
  assert.match(pluginSource, /for propertyName in pairs\(propertyNames\) do\s+local value = safeGetProperty\(instance, propertyName\)/);
});

test("Roblox plugin filters reserved RBX attributes during sync", () => {
  assert.match(pluginSource, /local function isReservedAttributeName\(attributeName\)\s+return type\(attributeName\) == "string" and \(string\.sub\(attributeName, 1, 3\) == "RBX" or attributeName == "AmarilloId"\)\s+end/);
  assert.match(pluginSource, /local function syncableAttributes\(attributes\)/);
  assert.equal((pluginSource.match(/syncableAttributes\(instance:GetAttributes\(\)\)/g) || []).length, 2);
  assert.match(pluginSource, /local desiredAttributes = syncableAttributes\(rawValue\)/);
  assert.match(pluginSource, /not isReservedAttributeName\(attributeName\) and desiredAttributes\[attributeName\] == nil/);
  assert.match(pluginSource, /for attributeName, attributeValue in pairs\(desiredAttributes\) do/);
});

test("Roblox plugin wraps mutating Studio writes in defensive helpers", () => {
  assert.match(pluginSource, /local function safeSetProperty\(target, propertyName, value, contextLabel\)/);
  assert.match(pluginSource, /local function safeSetAttribute\(target, attributeName, value, contextLabel\)/);
  assert.match(pluginSource, /local function safeSetParent\(target, newParent, contextLabel\)/);
  assert.match(pluginSource, /local okProperty, propertyErr = setProperty\(instance, propName, rawValue\)/);
  assert.match(pluginSource, /local okParent, parentErr = safeSetParent\(newInstance, parent, "MCP create parent"\)/);
  assert.doesNotMatch(pluginSource, /instance\[propertyName\]\s*=/);
  assert.equal((pluginSource.match(/:SetAttribute\(/g) || []).length, 1);
  assert.equal((pluginSource.match(/\.Parent\s*=(?!=)/g) || []).length, 1);
});

test("Roblox plugin aggregates safe-set failures for Doctor diagnostics", () => {
  assert.match(pluginSource, /local SAFE_SET_ERROR_DEDUPE_SECONDS = 30\.0/);
  assert.match(pluginSource, /local SAFE_SET_FAILURE_REPORT_LIMIT = 10/);
  assert.match(pluginSource, /local function beginSafeSetFailureAggregation\(command\)/);
  assert.match(pluginSource, /local function recordSafeSetFailure\(operation, target, fieldName, err, contextLabel, extraContext\)/);
  assert.match(pluginSource, /local function finishSafeSetFailureAggregation\(cycle\)/);
  assert.match(pluginSource, /recordSafeSetFailure\("property", target, propertyName, err, contextLabel\)/);
  assert.match(pluginSource, /recordSafeSetFailure\("attribute", target, attributeName, err, contextLabel\)/);
  assert.match(pluginSource, /recordSafeSetFailure\("parent", target, "Parent", err, contextLabel/);
  assert.match(pluginSource, /local safeSetCycle = beginSafeSetFailureAggregation\(command\)/);
  assert.match(pluginSource, /finishSafeSetFailureAggregation\(safeSetCycle\)/);
  assert.match(pluginSource, /safeSetFailureKey\(failure\.operation, failure\.instance, fieldName, failure\.error, cycle\.reason\)/);
  assert.match(pluginSource, /reportPluginError\(message, "PLUGIN-SAFE-SET", \{/);
  assert.match(pluginSource, /totalFailures = totalFailures,[\s\S]+uniqueFailures = #failures,[\s\S]+failures = limitedFailures/);
});

test("Roblox plugin preserves nested exclusive mount containers during sync", () => {
  assert.match(pluginSource, /local function buildNestedMountChildIndex\(mounts\)/);
  assert.match(pluginSource, /local function isNestedMountChild\(indexed, parentSegments, childName\)/);
  assert.match(pluginSource, /not isNestedMountChild\(nestedMountChildIndex, mountSegments, child\.Name\) and shouldIncludeSnapshotChild/);
  assert.match(pluginSource, /not isNestedMountChild\(nestedMountChildIndex, mount\.segments or \{\}, child\.Name\) and not isNonSyncableInstance/);
});

test("Roblox plugin verifies apply snapshots against the applied tree without preserved Studio-only nodes", () => {
  assert.match(pluginSource, /local shouldDestroyUnexpectedChild = nil/);
  assert.match(pluginSource, /local function isOpaqueModelInstance\(instance\)/);
  assert.match(pluginSource, /if isOpaqueModelInstance\(instance\) then\s+return false\s+end/);
  assert.match(pluginSource, /local function shouldPreserveUnknownChildDuringApply\(child, parentDesiredNode\)/);
  assert.match(pluginSource, /options and options\.omitPreservedUnknowns == true and shouldPreserveUnknownChildDuringApply/);
  assert.match(pluginSource, /local referenceSnapshot = options\.desiredSnapshot or state\.treeCache/);
  assert.match(pluginSource, /appliedSnapshot = snapshotCurrentProject\(\{\s+desiredSnapshot = projectSnapshot,\s+omitPreservedUnknowns = true\s+\}\)/);
});

test("Roblox plugin accepts the selected source of truth without blocking on diff preview", () => {
  assert.match(pluginSource, /local function choosePcTruth\(\)\s+acceptPendingConnection\("pc"\)\s+end/);
  assert.match(pluginSource, /local function chooseStudioTruth\(\)\s+acceptPendingConnection\("studio"\)\s+end/);
});

test("Roblox plugin retries the initial Studio source-of-truth snapshot", () => {
  assert.match(pluginSource, /awaitingInitialStudioSync = false/);
  assert.match(pluginSource, /local function attemptInitialStudioSync/);
  assert.match(pluginSource, /syncSnapshot\("initial_accept"\)/);
  assert.match(pluginSource, /Initial Studio sync still pending/);
  assert.match(pluginSource, /attemptInitialStudioSync\("retry", false\)/);
});

test("Roblox plugin surfaces sync diagnostics and sends place identity with connection requests", () => {
  assert.match(pluginSource, /warn\("\[Amarillo\] " \.\. tostring\(message\)\)/);
  assert.match(pluginSource, /MarketplaceService = game:GetService\("MarketplaceService"\)/);
  assert.match(pluginSource, /MarketplaceService:GetProductInfo\(placeId\)/);
  assert.match(pluginSource, /local fallback = tostring\(game\.Name or ""\)/);
  assert.match(pluginSource, /request\("POST", "\/connection\/diff", \{\s+placeId = game\.PlaceId,/);
  assert.match(pluginSource, /placeName = currentPlaceName\(\)/);
  assert.match(pluginSource, /request\("POST", "\/connection\/accept", \{\s+offerId = context\.offerId,[\s\S]+placeName = currentPlaceName\(\)/);
  assert.match(pluginSource, /PLACE_SETUP_REQUIRED/);
});

test("Roblox plugin UI construction keeps local registers below Studio limits", () => {
  assert.match(pluginSource, /local function initializeUiModule\(\)/);
  assert.match(pluginSource, /state\.uiActions = state\.uiActions or \{\}/);
  assert.match(pluginSource, /state\.uiActions\.pollConnectionOffer = function\(\)/);
  assert.match(pluginSource, /local reqOk, reqResponse = state\.uiActions\.pollConnectionOffer\(\)/);
  assert.match(pluginSource, /local function buildPluginShell\(\)/);
  assert.match(pluginSource, /local function buildHomePage\(\)\s+local homeHero = makeCard/);
  assert.match(pluginSource, /local function buildSettingsPage\(\)\s+local settingsHeader = makeCard/);
  assert.match(pluginSource, /local function buildAdvancedPage\(\)\s+local advancedHeader = makeCard/);
  assert.match(pluginSource, /local function buildDiffOverlay\(root\)\s+state\.ui\.diffOverlay = Instance\.new\("Frame"\)/);
  assert.match(pluginSource, /local function createPluginUi\(\)/);
  assert.match(pluginSource, /createPluginUi\(\)\s+end\s+initializeUiModule\(\)/);
});

test("Amarillo component versions stay synchronized from amarillo-version.json", () => {
  const extensionManifest = JSON.parse(fs.readFileSync(
    path.join(__dirname, "..", "vscode-extension", "package.json"),
    "utf8"
  ));
  const rootPackage = JSON.parse(fs.readFileSync(
    path.join(__dirname, "..", "package.json"),
    "utf8"
  ));
  const daemonVersionSource = fs.readFileSync(
    path.join(__dirname, "..", "src", "daemon", "version.js"),
    "utf8"
  );
  const extensionSource = fs.readFileSync(
    path.join(__dirname, "..", "vscode-extension", "extension.js"),
    "utf8"
  );

  assert.equal(extensionManifest.version, version.extensionVersion);
  assert.equal(rootPackage.version, version.extensionVersion);
  assert.match(daemonVersionSource, new RegExp(`const DAEMON_VERSION = "${version.daemonVersion}"`));
  assert.match(daemonVersionSource, new RegExp(`const CURRENT_PLUGIN_VERSION = "${version.pluginVersion}"`));
  assert.match(daemonVersionSource, new RegExp(`const AMARILLO_PROTOCOL_VERSION = ${version.protocolVersion}`));
  assert.match(pluginSource, new RegExp(`local PLUGIN_VERSION = "${version.pluginVersion}"`));
  assert.match(pluginSource, new RegExp(`local AMARILLO_PROTOCOL_VERSION = ${version.protocolVersion}`));
  assert.match(extensionSource, new RegExp(`const AMARILLO_PROTOCOL_VERSION = ${version.protocolVersion}`));
});
