"use strict";

const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const pluginSourceRoot = path.join(repoRoot, "src", "plugin-src");
const manifestPath = path.join(pluginSourceRoot, "manifest.json");
const generatedPluginPath = path.join(repoRoot, "src", "plugin", "Amarillo.lua");

const generatedBanner = [
  "-- This file is generated by scripts/build-plugin.ts.",
  "-- Edit src/plugin-src/*.lua and run npm.cmd run build:plugin instead.",
  ""
].join("\n");

function readManifest() {
  const parsed = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const modules = Array.isArray(parsed.modules) ? parsed.modules : [];
  if (modules.length === 0) {
    throw new Error("Plugin manifest must contain a non-empty modules array.");
  }
  const seen = new Set();
  for (const moduleName of modules) {
    if (typeof moduleName !== "string" || !moduleName.endsWith(".lua")) {
      throw new Error(`Invalid plugin module entry: ${moduleName}`);
    }
    if (moduleName.includes("/") || moduleName.includes("\\") || moduleName.includes("..")) {
      throw new Error(`Plugin module paths must stay inside src/plugin-src: ${moduleName}`);
    }
    if (seen.has(moduleName)) {
      throw new Error(`Duplicate plugin module entry: ${moduleName}`);
    }
    seen.add(moduleName);
  }
  return modules;
}

function normalizePluginModuleSource(source) {
  // Roblox compiles the concatenated plugin as one Luau chunk. Keeping every
  // module-level helper local eventually exceeds Luau's 200-local-register
  // limit, so generated module functions stay visible across fragments while
  // source fragments can keep their normal local-function style.
  return source.replace(/^local function /gm, "function ");
}

function readModule(moduleName) {
  const modulePath = path.join(pluginSourceRoot, moduleName);
  if (!fs.existsSync(modulePath)) {
    throw new Error(`Plugin module not found: ${moduleName}`);
  }
  const source = normalizePluginModuleSource(fs.readFileSync(modulePath, "utf8").replace(/\s+$/g, ""));
  return [
    `-- >>> src/plugin-src/${moduleName}`,
    source,
    `-- <<< src/plugin-src/${moduleName}`
  ].join("\n");
}

function generatePluginSource() {
  const modules = readManifest();
  return generatedBanner + modules.map(readModule).join("\n\n") + "\n";
}

function buildPlugin() {
  const source = generatePluginSource();
  fs.mkdirSync(path.dirname(generatedPluginPath), { recursive: true });
  fs.writeFileSync(generatedPluginPath, source, "utf8");
  process.stdout.write(`[build-plugin] Generated ${path.relative(repoRoot, generatedPluginPath)} from ${readManifest().length} module(s).\n`);
  return source;
}

if (require.main === module) {
  buildPlugin();
}

module.exports = {
  repoRoot,
  pluginSourceRoot,
  manifestPath,
  generatedPluginPath,
  generatedBanner,
  readManifest,
  normalizePluginModuleSource,
  generatePluginSource,
  buildPlugin
};
